[tool.poetry]
name = "gt4sd"
version = "0.1.0"
license="MIT"
description = "Openad_model_Service"
authors = ["Daniel Choi <choi@ibm.com>", "Phil Downey <Phil.Downey1@ibm.com>", "Brian Duenas <Brian.Duenas@ibm.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"

gt4sd_inference_guacamol = { path = "gt4sd/gt4sd_guacamol" }
gt4sd-inference-moler = { path = "gt4sd/gt4sd_moler"}
gt4sd-inference-regression = { path = "gt4sd/gt4sd_regression" }
gt4sd-inference-reinvent = { path = "gt4sd/gt4sd_reinvent" }
gt4sd-inference-torch-drug = { path = "gt4sd/gt4sd_torch" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
fix = true
line-length = 88
target-version = "py310"
show-fixes = true

[tool.ruff.lint]
ignore = [
    "E722", # Do not use bare `except`
    "F401", # imported but unused
    "E402", # gt4sd top level submodule
]
